# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: PACKAGE VERSION\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2014-12-03 16:41+0100\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"Language: \n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=CHARSET\n"
"Content-Transfer-Encoding: 8bit\n"

#: ../usr/lib/ddm/ati.py:73
#, python-format
msgid "ATI card found: %(card)s"
msgstr ""

#: ../usr/lib/ddm/ati.py:78
#, python-format
msgid "ATI chip serie found: %(serie)s"
msgstr ""

#: ../usr/lib/ddm/ati.py:87
#, python-format
msgid "ATI driver found: %(drv)s (%(status)s)"
msgstr ""

#: ../usr/lib/ddm/ati.py:90 ../usr/lib/ddm/via.py:56
#: ../usr/lib/ddm/intel.py:57 ../usr/lib/ddm/nvidia.py:104
#, python-format
msgid "Driver not installable: %(drv)s"
msgstr ""

#: ../usr/lib/ddm/ati.py:92
#, python-format
msgid "ATI chip serie not supported: %(serie)d"
msgstr ""

#: ../usr/lib/ddm/ati.py:94
#, python-format
msgid "No driver found for: %(card)s (%(man)s:%(serie)s)"
msgstr ""

#: ../usr/lib/ddm/ati.py:107 ../usr/lib/ddm/via.py:68
#: ../usr/lib/ddm/intel.py:69 ../usr/lib/ddm/nvidia.py:118
#, python-format
msgid "Install driver: %(drv)s"
msgstr ""

#: ../usr/lib/ddm/ati.py:121 ../usr/lib/ddm/nvidia.py:144
#, python-format
msgid "Switch to module: %(module)s"
msgstr ""

#: ../usr/lib/ddm/ati.py:127 ../usr/lib/ddm/via.py:77
#: ../usr/lib/ddm/intel.py:78 ../usr/lib/ddm/nvidia.py:154
#, python-format
msgid "Driver installed: %(drv)s"
msgstr ""

#: ../usr/lib/ddm/ati.py:138
msgid "Removing ATI drivers"
msgstr ""

#: ../usr/lib/ddm/ati.py:152 ../usr/lib/ddm/via.py:96
#: ../usr/lib/ddm/intel.py:97 ../usr/lib/ddm/nvidia.py:183
#, python-format
msgid "Driver removed: %(drv)s"
msgstr ""

#: ../usr/lib/ddm/ati.py:160
msgid "ATI display driver"
msgstr ""

#: ../usr/lib/ddm/ati.py:162 ../usr/lib/ddm/intel.py:105
#: ../usr/lib/ddm/nvidia.py:193
msgid "Intel display driver"
msgstr ""

#: ../usr/lib/ddm/ati.py:164
msgid "Radeon display driver"
msgstr ""

#: ../usr/lib/ddm/ati.py:166 ../usr/lib/ddm/via.py:106
#: ../usr/lib/ddm/intel.py:107 ../usr/lib/ddm/nvidia.py:197
msgid "Framebuffer display driver"
msgstr ""

#: ../usr/lib/ddm/ati.py:168 ../usr/lib/ddm/via.py:108
#: ../usr/lib/ddm/intel.py:109 ../usr/lib/ddm/nvidia.py:199
msgid "Vesa display driver"
msgstr ""

#: ../usr/lib/ddm/broadcom.py:89
#, python-format
msgid "Broadcom chip serie found: %(chip)s"
msgstr ""

#: ../usr/lib/ddm/broadcom.py:158
#, python-format
msgid "Used wireless driver: %(drv)s"
msgstr ""

#: ../usr/lib/ddm/broadcom.py:179
#, python-format
msgid "Broadcom found: %(broadcom)s"
msgstr ""

#: ../usr/lib/ddm/broadcom.py:202
#, python-format
msgid "Broadcom chipset not supported or ethernet controller: %(broadcom)s"
msgstr ""

#: ../usr/lib/ddm/broadcom.py:204
#, python-format
msgid "Broadcom chipset not found: %(chip)s"
msgstr ""

#: ../usr/lib/ddm/broadcom.py:207
#, python-format
msgid "Broadcom pci ID not found: %(id)s"
msgstr ""

#: ../usr/lib/ddm/broadcom.py:216
#, python-format
msgid "Linux header name to install: %(header)s"
msgstr ""

#: ../usr/lib/ddm/broadcom.py:220
#, python-format
msgid "Download package: %(package)s"
msgstr ""

#: ../usr/lib/ddm/broadcom.py:228
#, python-format
msgid "Download package: %(drv)s"
msgstr ""

#: ../usr/lib/ddm/broadcom.py:265
msgid "Install downloaded packages"
msgstr ""

#: ../usr/lib/ddm/broadcom.py:273
#, python-format
msgid "Reconfigure package: %(package)s"
msgstr ""

#: ../usr/lib/ddm/broadcom.py:316
#, python-format
msgid "Purge driver: %(drv)s"
msgstr ""

#: ../usr/lib/ddm/broadcom.py:326
msgid "Done removing Broadcom drivers"
msgstr ""

#: ../usr/lib/ddm/xorg.py:81
#, python-format
msgid "Used graphics driver: %(module)s"
msgstr ""

#: ../usr/lib/ddm/xorg.py:103
msgid "No xorg.conf - create minimal xorg.conf"
msgstr ""

#: ../usr/lib/ddm/xorg.py:123
msgid "New xorg.conf written"
msgstr ""

#: ../usr/lib/ddm/xorg.py:129
msgid "New section appended to xorg.conf"
msgstr ""

#: ../usr/lib/ddm/via.py:47
#, python-format
msgid "Via card found: %(card)s"
msgstr ""

#: ../usr/lib/ddm/via.py:53
#, python-format
msgid "Via driver found: %(drv)s (%(status)s)"
msgstr ""

#: ../usr/lib/ddm/via.py:104
msgid "Chrome display driver"
msgstr ""

#: ../usr/lib/ddm/intel.py:48
#, python-format
msgid "Intel card found: %(card)s"
msgstr ""

#: ../usr/lib/ddm/intel.py:54
#, python-format
msgid "Intel driver found: %(drv)s (%(status)s)"
msgstr ""

#: ../usr/lib/ddm/ddm.py:72
msgid "Graphics"
msgstr ""

#: ../usr/lib/ddm/ddm.py:73
msgid "Wireless"
msgstr ""

#: ../usr/lib/ddm/ddm.py:74
msgid "Kernel"
msgstr ""

#: ../usr/lib/ddm/ddm.py:75
msgid "Hardware"
msgstr ""

#: ../usr/lib/ddm/ddm.py:76
msgid "Activated driver"
msgstr ""

#: ../usr/lib/ddm/ddm.py:77
msgid "Alternative drivers"
msgstr ""

#: ../usr/lib/ddm/ddm.py:116 ../usr/lib/ddm/ddm.py:147
msgid "Current drivers are correct"
msgstr ""

#: ../usr/lib/ddm/ddm.py:157
msgid "PAE already installed"
msgstr ""

#: ../usr/lib/ddm/ddm.py:159
msgid "PAE support only for 32-bit systems"
msgstr ""

#: ../usr/lib/ddm/ddm.py:199
msgid "Activate"
msgstr ""

#: ../usr/lib/ddm/ddm.py:199
msgid "Driver"
msgstr ""

#: ../usr/lib/ddm/ddm.py:199
msgid "Version"
msgstr ""

#: ../usr/lib/ddm/ddm.py:199
msgid "Description"
msgstr ""

#: ../usr/lib/ddm/ddm.py:214
msgid " (recommended)"
msgstr ""

#: ../usr/lib/ddm/ddm.py:259
msgid "Unknown driver"
msgstr ""

#: ../usr/lib/ddm/ddm.py:262
msgid ""
"Unknown driver found.\n"
"\n"
"Please remove before installing drivers with DDM."
msgstr ""

#: ../usr/lib/ddm/ddm.py:307
msgid "Driver activation"
msgstr ""

#: ../usr/lib/ddm/ddm.py:307
#, python-format
msgid ""
"Are you sure you want to install the following driver:\n"
"\n"
"%(drv)s"
msgstr ""

#: ../usr/lib/ddm/ddm.py:312 ../usr/lib/ddm/ddm.py:452
msgid "Locked"
msgstr ""

#: ../usr/lib/ddm/ddm.py:312
#, python-format
msgid ""
"Could not get lock on %(file)s.\n"
"\n"
"Close any programs locking the file and try again."
msgstr ""

#: ../usr/lib/ddm/ddm.py:390
msgid "Driver installed"
msgstr ""

#: ../usr/lib/ddm/ddm.py:390
#, python-format
msgid ""
"Driver installed: %(drv)s\n"
"\n"
"Drivers will be used on next boot.\n"
"Do you want to reboot now?"
msgstr ""

#: ../usr/lib/ddm/ddm.py:452
#, python-format
msgid ""
"Could not get lock on %(file)s.\n"
"\n"
"Close any programs locking the file and restart DDM."
msgstr ""

#: ../usr/lib/ddm/ddm.py:485
msgid "Checking your hardware..."
msgstr ""

#: ../usr/lib/ddm/ddm.py:550
msgid "Start automatic driver install"
msgstr ""

#: ../usr/lib/ddm/pae.py:43
#, python-format
msgid "Installed PAE: %(pae)s"
msgstr ""

#: ../usr/lib/ddm/pae.py:49
msgid "Multi-core support for 32-bit systems"
msgstr ""

#: ../usr/lib/ddm/pae.py:59
#, python-format
msgid "Multi-core already installed: %(package)s"
msgstr ""

#: ../usr/lib/ddm/pae.py:60 ../usr/lib/ddm/pae.py:73
msgid "PAE capable system"
msgstr ""

#: ../usr/lib/ddm/pae.py:66
msgid "Multi-core system running single-core kernel found"
msgstr ""

#: ../usr/lib/ddm/pae.py:70
msgid "PAE not installed"
msgstr ""

#: ../usr/lib/ddm/pae.py:79
msgid "PAE kernel cannot be installed: single-core system"
msgstr ""

#: ../usr/lib/ddm/pae.py:95
msgid "Done installing PAE"
msgstr ""

#: ../usr/lib/ddm/pae.py:109
#, python-format
msgid "PAE package to remove: %(package)s"
msgstr ""

#: ../usr/lib/ddm/pae.py:112
msgid "Done removing PAE"
msgstr ""

#: ../usr/lib/ddm/pae.py:114
msgid "Cannot remove PAE when running PAE"
msgstr ""

#: ../usr/lib/ddm/nvidia.py:57
msgid "Update apt"
msgstr ""

#: ../usr/lib/ddm/nvidia.py:60
msgid "Install nvidia-detect"
msgstr ""

#: ../usr/lib/ddm/nvidia.py:68
msgid "Cannot install nvidia-detect: abort"
msgstr ""

#: ../usr/lib/ddm/nvidia.py:92
#, python-format
msgid "Nvidia card found: %(card)s"
msgstr ""

#: ../usr/lib/ddm/nvidia.py:101
#, python-format
msgid "Nvidia driver found: %(drv)s (%(status)s)"
msgstr ""

#: ../usr/lib/ddm/nvidia.py:166
msgid "Removing Nvidia drivers"
msgstr ""

#: ../usr/lib/ddm/nvidia.py:191
msgid "Nvidia display driver"
msgstr ""

#: ../usr/lib/ddm/nvidia.py:195
msgid "Nouveau display driver"
msgstr ""

#: ../usr/lib/ddm/main.py:67
#, python-format
msgid "Write debug information to file: %(path)s"
msgstr ""

#: ../usr/lib/ddm/main.py:71
#, python-format
msgid "Machine info: %(info)s"
msgstr ""

#: ../usr/lib/ddm/main.py:73
#, python-format
msgid "DDM version: %(version)s"
msgstr ""

#: ../usr/lib/ddm/main.py:78
msgid "apt-listbugs is installed and might interfere with driver installation"
msgstr ""

#: ../usr/lib/ddm/main.py:108 ../usr/lib/ddm/main.py:110
msgid "Please enter your password"
msgstr ""

#: ../usr/lib/ddm/main.py:116
msgid "DDM - Kernel"
msgstr ""

#: ../usr/lib/ddm/main.py:117
msgid ""
"You do not have the latest kernel installed.\n"
"\n"
"Use the Update Manager to update your system."
msgstr ""

#: ../usr/lib/ddm/main.py:121
msgid "DDM - Live environment"
msgstr ""

#: ../usr/lib/ddm/main.py:122
msgid ""
"DDM cannot run in a live environment\n"
"\n"
"To force start, use the --force argument"
msgstr ""

#: ../usr/lib/ddm/main.py:126
msgid "DDM - Debian based"
msgstr ""

#: ../usr/lib/ddm/main.py:127
msgid ""
"Cannot determine the base distribution (debian or ubuntu)\n"
"\n"
"To force start, use the --force argument"
msgstr ""

#: ../usr/lib/ddm/main.py:131
msgid "DDM - Internet"
msgstr ""

#: ../usr/lib/ddm/main.py:132
msgid ""
"You do not seem to have an internet connection\n"
"\n"
"To force start, use the --force argument"
msgstr ""

#: ../usr/share/applications/ddm.desktop.in.h:1
msgid "Device Driver Manager"
msgstr ""
